### ISSUE TITLE
Epic and Backlogs for "Apply New Client Number App"

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forest-client#50]
[FSADT1-373](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-373) [Proof-of-Concept - Creation of Forest Client Account - Team Alliance - Confluence (gov.bc.ca)](https://apps.nrs.gov.bc.ca/int/confluence/display/FSADT1/Proof-of-Concept+-+Creation+of+Forest+Client+Account)

[New client application form](https://bcgov.sharepoint.com/teams/03678-Servicedesign/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2F03678%2DServicedesign%2FShared%20Documents%2FService%20design%2FCLIENT%2FClient%20Information%20Form%20%28FS1377%29%202020%20%28003%29%2Epdf&parent=%2Fteams%2F03678%2DServicedesign%2FShared%20Documents%2FService%20design%2FCLIENT&p=true&ga=1)

Do we support updating existing client? No
Do we disable old client application creating client? Yes

### **New client form:**
**Frontend:**
- [x] Login flow for business and individual user, business bceid and bc service card
- [x] Get user information after login (username, email or so, depends on what returns by pathfinder sso login project)
- [x] Call backend api to check duplicate [sprint 13 - [FSADT1-480](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-480)]
- [x] If no duplication, auto populate basic information into a new user form
- [x] If duplicate, show a warning message to them, to see if they want to update information, or forget the client id, or what they will do 
- [x] Create reusable form components and unit tests (input, dropdown, multi select, single select, table) [spring 12 - [FSADT1-449](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-449)]
- [x] Create form schema [spring 12 - [FSADT1-449](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-449)]
      - [x] create more form components (radio, table, group)
      - [x] create form structure that support json schema
      - [x] get the idea and create function to check if all required field has been entered
      - [x] add form logic for pre-request, hide or show content based on the value of a field
- [x] Show landing page first, and then login, https://stackoverflow.com/questions/65020000/using-keycloak-in-vue3-but-not-on-startup
- [x] Auto complete dropdown select that connects to orgbook/bc registry for company name
- [ ] Date pick component [sprint 13 - [FSADT1-479](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-479)]
- [x] Auto fill address 
- [x] Pop up modal to confirm a user wants to submit the form [spring 11 - [FSADT1-441]
- [x] Call backend data validation api, and display error message if has any returned
- [x] Write a screen for submission success/failure [spring 11 - [FSADT1-441](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-441)]
- [x] **If need send any notification email to specific reviewer?**
 
**Backend:**
- [x] Get user linked business information though bc registry api or orgbook, **can we get the information for individual?**
- [x] Create api to check possible duplicate by exact match(search for client name, incorporation number, legal first/middle name, dob) [spring 12 - [FSADT1-426](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-426)]
- [x] Add CHES email service for sending confirmation email [spring 11 - [FSADT1-441](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-441)]
- [x] Create api to get client type, call the api from frontend to get the options [sprint 13 - [FSADT1-477](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-477)]
- [x] Create api to get client contact type, call the api from frontend to get the options [sprint 13 - [FSADT1-478](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-478)]
- [x] Data validation and return error messages to frontend
- [ ] Create api to check if already has a pending submission for this user
- [x] Create api to write new client information into postgres database
- [x] Upgrade java apps to SpringBoot V.3 [FSADT1-435](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-435) [Done for Forest Client, Pending for Forest Client API]
- [x] Fix Swagger page after the upgrade of SpringBoot v3. [FSADT1-435](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-435)
- [x] using vault for oracle db proxy account in pipeline

**Database**
- [x] Create data model in postgres for submission tables to save new client submission data [spring 12 - [FSADT1-436](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-436)]
- [x] Create entities and all related classes to support the DB in the backend (Java)

### **New client review their submission** (might don't need this for now):
- [ ] a tab screen for them to review their submission status
- [ ] **allow them update their submission information?**
- [ ] create api to update submission information

### **Review client application:**
- [x] login using idir
- [x] a tab screen for **all submissions, or submissions assign to that person?**, design list view
- [x] Create api to check possible duplicate by exact match
- [x] allow them to change submission status, **what the status will be**? submitted, pending, reviewing, approved, rejected, revised
- [ ] **allow them to edit submission?**
- [x] sync new client data back to oracle once it got approval
- [x] **how to get client the client number generated in oracle?**

### **Others:**
- [x] **If allow attach files?**
- [x] design different tab screen for idir and bceid user [sprint 11 - [FSADT1-430](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-430)]
- [ ] write sql trigger error handling to prevent old client application creating new client
- [ ] Observation check for openshift pods
- [ ] Db backup and restore
- [x] API Gateway for any external apis we provide
- [x] Pipeline upgrade
- [x] merge nr-forst-client-api in
- [x] separate Postgres/oracle connection into two apps under same repo backend folder
- [ ] oracle client tables audit, jira: https://apps.nrs.gov.bc.ca/int/jira/browse/INFRA-18068

**Comment by MCatherine1994** [comment]
a test example for what bceid user returns:
![image](https://user-images.githubusercontent.com/23131735/191381031-fb41c037-ba91-4e3e-9612-6fd1f430f371.png)

a test example for what idir user returns:
<img width="499" alt="Screen Shot 2022-09-20 at 4 23 50 PM" src="https://user-images.githubusercontent.com/23131735/191381915-352d8d65-bc5b-412f-bed4-b380cd01ec55.png">
